version: "3"
services:
  master:
    build:
      context: ./
      dockerfile: Dockerfile.master
    container_name: master
    restart: unless-stopped
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: pass
    networks:
      - database-network

  replica:
    build:
      context: ./
      dockerfile: Dockerfile.replica
    container_name: replica
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: pass
    depends_on:
      - master
    networks:
      - database-network

networks:
  database-network:
    driver: bridge
